name: Release binary

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clone deps
      run: |
        git submodule init
        git submodule update

    - name: Build
      run: make -j`nproc`

    - name: Package
      run: |
        strip  ff
        md5sum ff > ff.md5

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ff
          ff.md5

